Mission5Assignment/Models/ErrorViewModel.cs
namespace Mission5Assignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mission5Assignment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mission5Assignment.Models;
using System.Diagnostics;

namespace Mission5Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mission5Assignment/Controllers/LessonsController.cs
using Microsoft.AspNetCore.Mvc;
using Mission5Assignment.Models;
using System.Diagnostics;

namespace Mission5Assignment.Controllers
{
    public class LessonsController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public LessonsController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Lessons()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mission5Assignment/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">About Caleb Gooch</h1>
    <p>
        When I was a freshman in high school, my good friends Riley and Trenton told me I should play tennis with him.
        None of us had ever played tennis before, but we all tried out and made the team. 
    </p>
    <img src="~/trenton.jpg" height="150px" />
    <p>
        Over the next four years, I played a lot of tennis and got significantly better, even going undefeated in singles during the regular season my senior year.
    </p>
    <img src="~/serve.jpg" height="150px" />
    <p>Now, I want to teach you to play!</p>
</div>

Mission5Assignment/Views/Lessons/Lessons.cshtml
<h1>Lessons With Me</h1>
<p>Below you can calulate the total for tennis lessons with me. I charge 5 dollars an hour since I get to enjoy playing as well</p>
<div>
    <label for="hours">Enter the number of hours you need:</label>
    <input type="text" id="hours" />
</div>
<div>
    <label>Charge per hour:</label>
    <input type="text" id="charge" value="50" readonly />
</div>
<div>
    <button id="calculate">Calculate Total</button>
</div>
<div>
    <label>Total:</label>
    <span id="total"></span>
</div>

Mission5Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Caleb Gooch's Page</title>
    <link rel="icon" href="~/tennis_ball_icon.png" type="image/png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mission5Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Caleb Gooch - Tennis Instructor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lessons" asp-action="Lessons">Lessons</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mission 5 Assignment - Built by Caleb Gooch
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>